services:
  applio:
    build:
      context: .
      target: runner
    volumes:
      - ./logs:/app/logs
      - ./assets:/app/assets
    ports:
      - 6969:6969
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
