services:
  applio:
    image: ghcr.io/pycabbage/applio:prebuild-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 16969:6969
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./logs:/app/logs
      - opt:/app/opt
      - ./rvc/pretraineds:/app/rvc/pretraineds
      - ./rvc/lib:/app/rvc/lib


volumes:
  opt:
