version: '1'

services:
  applio:
    image: ghcr.io/IAHispano/applio:master
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6969"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
